export const paths = {
  root: '/',
  login: '/login',
  welcome: '/welcome',
  system: '/system',
  userManagement: '/system/user-management',
  roleManagement: '/system/role-management',
  menuManagement: '/system/menu-management',
  forbidden: '/403',
  notFound: '/404',
  redirect4develop: '/login-redirect',
  cases: 'cases',
  cm: 'cm',
  le: 'le',
  meetingHolder: 'meeting-holder',
  nev: 'nev',
}
